### ISSUE TITLE
sticky doesn't seem to work with react-table integrating react-window

### ISSUE THREAD

**Issue by akramer24** [GuillaumeJasmin/react-table-sticky#7]
One of the perks to react-table v7 is the ability to integrate react-window's FixedSizeList to create a virtualized table. Unfortunately, it seems react-table-sticky doesn't work when using FixedSizeList as the table body component -- the header cells of `sticky: 'left'` columns are indeed sticky, but the cells move. With the same setup of react-table-sticky but replacing FixedSizeList with a standard mapping of divs as the body, I can get sticky columns. Is this library meant to handle the FixedSizeList/react-window integration in react-table?

For now, I have a workaround where I am putting two FixedSizeLists adjacent to each other in the body and using their scrollTo/onScroll methods to stay in sync.

**Comment by GuillaumeJasmin** [comment]
I @akramer24 !
Thanks for your feedback.
There is already an issue about react-window, see #5 .
It seems react-table-sticky and react-window are incompatible because react-window add some new levels of `<div>` and that break the native CSS sticky property, but I haven't take time to investigate more about that.
I close this issue, so please continue on #5  

Thank you :)

**Comment by akramer24** [comment]
Cool, thanks for the response.
